---
title: "Resources"
---

Here you will find a list of resources which will be useful during this course.

# Books

In short my recommendation is:

Focus your efforts on [IMS2](https://openintro-ims.netlify.app/) as it covers experimental design, statistics and how to present results. To better understand a data analysis workflow, use [R4DS](https://r4ds.hadley.nz/) and [MD2](https://moderndive.com/v2/). For help with a basic programming concept, consult [HOPR](https://rstudio-education.github.io/hopr/). For alternative explanations of statistical approaches, use [MD2](https://moderndive.com/v2/) and [StatBio](https://bradduthie.github.io/stats/).

#### [Introduction to Modern Statistics, 2nd ed,. Çetinkaya-Rundel & Hardin (2024)](https://openintro-ims.netlify.app/){target="_blank"}

**Main course book (IMS2)** 

Good for:

- All the statistical methods we cover in this course
- General advice for making figures and presenting results
- Introductory level explanations of theory
- Simple practical exercises (see *Applications* sections)

Not so good for:

- How to do something in R
- Deeper explanations of statistical methods
- Biological examples (most examples are from social sciences / business)

#### [Statistical Inference via Data Science 2nd ed., Ismay, Kim & Valdivia (2025)](https://moderndive.com/v2/){target="_blank"}

**(MD2)**

Good for:

- Alternative explanation of some statistical methods we cover in this course
- R code examples simple data handling, plotting and analysis
- Simple coding exercises to help understand core concepts

Not so good for:

- Anything multivariate
- Biological examples (most examples are from social sciences / business)
- More advanced R problems

#### [R for Data Science, 2nd ed., Wickham, Çetinkaya-Rundel & Grolemund (2023)](https://r4ds.hadley.nz/){target="_blank"}

**(R4DS)**

Good for:

- R code for importing, handling, cleaning and plotting data with `tidyverse`
- Help with Quarto documents

Not so good for:

- Statistics
- Core R programming concepts

#### [Hands-On Programming with R, Grolemund (2018)](https://rstudio-education.github.io/hopr/){target="_blank"}

**(HOPR)**

Good for:

- Basic introduction to R
- Core R programming concepts

Not so good for:

- Tidyverse packages
- Statistics

#### [Fundamental statistical concepts and techniques in the biological and environmental sciences, 1st ed. Duthie (2025)](https://bradduthie.github.io/stats/){target="_blank"}

**(StatBio)**

Good for:

- Theory based statistics
- Biological examples
- Basic introduction to classical frequentist statistical methods
- Also available as an [audiobook](https://bradduthie.github.io/audiobook.html){target="_blank"}

Not so good for:

- R code
- Randomisation and simulation based inference

---

# Software

During the course we will use R and RStudio as tools to handle data, make plots and do statistics.

- [The R Project for Statistical Computing](https://www.r-project.org/){target="_blank"}
- [RStudio Desktop](https://posit.co/download/rstudio-desktop/){target="_blank"}

If you want to use another software package for these purposes, you are very welcome to, but you do so at your own undertaking.

We will make use of a set of R packages that are part of the extended `tidyverse` set of packages. Below are the websites for the main ones we will use, which contain guides, "cheatsheets" and reference materials.

#### General

- [`tidyverse`](https://www.tidyverse.org/){target="_blank"}
  - [`ggplot2`](https://ggplot2.tidyverse.org/){target="_blank"} (Plotting data)
  - [`dplyr`](https://dplyr.tidyverse.org/){target="_blank"} (Manipulating data)
  - [`tidyr`](https://tidyr.tidyverse.org/){target="_blank"} (Tidying data)
  - [`readr`](https://readr.tidyverse.org/){target="_blank"} (Importing/exporting data)

#### Statistics

- [`infer`](https://infer.tidymodels.org/){target="_blank"}